main:
    component_repository: "https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#components"
    project_name: NYC_AirBNB
    experiment_name: development
    steps: all

etl_configs:
    data_file: "sample1.csv"
    min_price: 10
    max_price: 350

data_checks:
    kl_threshold: 0.2

modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 15
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
    criterion: squared_error
    max_features: 0.5
    oob_score: true
  output_artifact: "random_forest_export" 


