wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1711384295.1401
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.16.0
      8:
      - 2
      - 4
      - 5
      - 13
      13: darwin-arm64
